AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: true
  Exclude:
    - 'bin/**/*'
    - 'Gemfile'
    - 'config/**/*'
    - 'test/**/*'
    - '.gitignore'
    - 'db/schema.rb'


Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
