AllCops:
  DisplayCopNames: true
  StyleGuideCopsOnly: true
  

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 100

Metrics/AbcSize:
  Max: 20
